services:
  backend:
    build:
      context: '../backend'
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: '../frontend'
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}