services:
  backend:
    container_name: springboot-backend
    build:
      context: '../backend'
      dockerfile: ../backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2

  frontend:
    container_name: react-frontend
    build:
      context: '../frontend'
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}